[build]
  # Build command - install dependencies and copy images
  command = "npm install && cd nodejs-app && npm install && cp ../*.png public/"
  
  # Directory to publish (where the static files are)
  publish = "nodejs-app/public"
  
  # Functions directory for serverless functions
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirect all routes to index.html for SPA behavior (except functions and assets)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variables (will be set in Netlify dashboard)
# GEMINI_API_KEY = "your_api_key_here"
